#!/usr/bin/env python3
"""Generate LIBRARIES.md from symbols/*.kicad_sym files."""

import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SYMBOLS_DIR = REPO_ROOT / "symbols"
OUTPUT = REPO_ROOT / "LIBRARIES.md"

_SYMBOL_SPLIT_RE = re.compile(r"(?=^\t\(symbol \")", re.MULTILINE)
_SYMBOL_NAME_RE = re.compile(r"^\t\(symbol \"([^\"]+)\"")
_DESC_RE = re.compile(r"\(property \"Description\" \"([^\"]*)\"")


def parse_library(path: Path) -> list[tuple[str, str]]:
    text = path.read_text(encoding="utf-8")
    symbols = []
    for chunk in _SYMBOL_SPLIT_RE.split(text):
        m = _SYMBOL_NAME_RE.match(chunk)
        if not m:
            continue
        name = m.group(1)
        # Skip graphical sub-units (e.g. "R_0402_1k_0_0")
        if re.search(r"_\d+_\d+$", name):
            continue
        desc_m = _DESC_RE.search(chunk)
        desc = desc_m.group(1).strip() if desc_m else ""
        symbols.append((name, desc))
    return symbols


def generate() -> str:
    libs: list[tuple[str, list[tuple[str, str]]]] = []
    for path in sorted(SYMBOLS_DIR.glob("*.kicad_sym")):
        symbols = parse_library(path)
        if symbols:
            libs.append((path.stem, symbols))

    lines = [
        "# GS KiCad Libraries",
        "",
        "<!-- Auto-generated by `scripts/generate-libraries-md.py`"
        " — run `make libraries` to update -->",
        "",
        "| Library | Components |",
        "|---|---|",
    ]
    for lib_name, symbols in libs:
        anchor = lib_name.lower().replace("_", "-")
        lines.append(f"| [{lib_name}](#{anchor}) | {len(symbols)} |")

    lines.append("")

    for lib_name, symbols in libs:
        lines.append(f"## {lib_name}")
        lines.append("")
        for name, desc in symbols:
            entry = f"- **{name}**"
            if desc:
                entry += f" — {desc}"
            lines.append(entry)
        lines.append("")

    return "\n".join(lines) + "\n"


def main() -> None:
    content = generate()
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
